[package]
name = "instrumenttest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walrus = "0.19.0"
clap = "2.33.3"
rmp-serde = "0.15.5"
serde = { version = "1.0.62", features = ["derive"] }
